name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.awsregion }}

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Plan Terraform'
        run: terraform plan -no-color

     # - name: Terraform Apply
     #   id: apply 
      #  if: ${{ github.event.inputs.terraform_action == 'apply' }}
      #  run: terraform apply
      
      - name: Terraform destroy
        id: destroy 
        #if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        run: terraform destroy -auto-approve